import { FlowConfigProvider, type IBaseWidgets } from "@baseflow/react";
import { Modal, message } from "antd";

function confirm(message: string, callback: (ok: boolean) => void, props?: { title?: string; okText?: string; cancelText?: string }): void {
  Modal.confirm({
    title: "提示",
    content: message,
    ...props,
    onOk() {
      callback(true);
    },
    onCancel() {
      callback(false);
    },
  });
}

const widgets: Partial<IBaseWidgets> = {
  message,
  confirm,
};

export default (props: { children: any }) => {
  return <FlowConfigProvider widgets={widgets}>{props.children}</FlowConfigProvider>;
};

export const IconList: string[] = [
  "DownOutlined",
  "UpOutlined",
  "LeftOutlined",
  "RightOutlined",
  "CaretUpOutlined",
  "CaretDownOutlined",
  "CaretLeftOutlined",
  "CaretRightOutlined",
  "UpCircleOutlined",
  "DownCircleOutlined",
  "LeftCircleOutlined",
  "RightCircleOutlined",
  "ArrowUpOutlined",
  "ArrowDownOutlined",
  "ArrowLeftOutlined",
  "ArrowRightOutlined",
  "UpSquareOutlined",
  "DownSquareOutlined",
  "LeftSquareOutlined",
  "RightSquareOutlined",
  "ForwardOutlined",
  "BackwardOutlined",
  "DoubleRightOutlined",
  "DoubleLeftOutlined",
  "RetweetOutlined",
  "SwapOutlined",
  "LoginOutlined",
  "LogoutOutlined",
  "MenuFoldOutlined",
  "MenuUnfoldOutlined",
  "PicLeftOutlined",
  "PicRightOutlined",
  "PicCenterOutlined",
  "ShrinkOutlined",
  "ArrowsAltOutlined",
  "FullscreenOutlined",
  "FullscreenExitOutlined",
  "PlayCircleOutlined",
  "PlayCircleFilled",
  "UpCircleFilled",
  "DownCircleFilled",
  "LeftCircleFilled",
  "RightCircleFilled",
  "QuestionOutlined",
  "QuestionCircleOutlined",
  "PlusOutlined",
  "PlusCircleOutlined",
  "PauseOutlined",
  "PauseCircleOutlined",
  "MinusOutlined",
  "MinusCircleOutlined",
  "PlusSquareOutlined",
  "MinusSquareOutlined",
  "InfoCircleOutlined",
  "ExclamationCircleOutlined",
  "CloseOutlined",
  "CloseCircleOutlined",
  "CloseSquareOutlined",
  "CheckOutlined",
  "CheckCircleOutlined",
  "CheckSquareOutlined",
  "ClockCircleOutlined",
  "WarningOutlined",
  "IssuesCloseOutlined",
  "StopOutlined",
  "QuestionCircleFilled",
  "PlusCircleFilled",
  "PauseCircleFilled",
  "MinusCircleFilled",
  "PlusSquareFilled",
  "MinusSquareFilled",
  "InfoCircleFilled",
  "ExclamationCircleFilled",
  "CloseCircleFilled",
  "CloseSquareFilled",
  "CheckCircleFilled",
  "CheckSquareFilled",
  "ClockCircleFilled",
  "WarningFilled",
  "StopFilled",
  "EditOutlined",
  "FormOutlined",
  "CopyOutlined",
  "ScissorOutlined",
  "DeleteOutlined",
  "SnippetsOutlined",
  "RedoOutlined",
  "UndoOutlined",
  "ZoomInOutlined",
  "ZoomOutOutlined",
  "SortAscendingOutlined",
  "SortDescendingOutlined",
  "FontColorsOutlined",
  "DragOutlined",
  "AlignCenterOutlined",
  "AlignLeftOutlined",
  "AlignRightOutlined",
  "OrderedListOutlined",
  "UnorderedListOutlined",
  "ColumnWidthOutlined",
  "ColumnHeightOutlined",
  "AreaChartOutlined",
  "LineChartOutlined",
  "BarChartOutlined",
  "DotChartOutlined",
  "PieChartOutlined",
  "SlidersOutlined",
  "AndroidOutlined",
  "AppleOutlined",
  "WindowsOutlined",
  "GithubOutlined",
  "QqOutlined",
  "WhatsAppOutlined",
  "AlipayCircleOutlined",
  "WechatOutlined",
  "RedditOutlined",
  "TikTokOutlined",
  "DockerOutlined",
  "OpenAIOutlined",
  "YoutubeOutlined",
];
